### ISSUE TITLE
Support for running mkxp-z in other platforms

### ISSUE THREAD

**Issue by Nathan-MV** [SnowSzn/rgss-script-editor#2]
mkxp-z has Mac and Linux binaries so we don't need to run it with Wine

**Comment by SnowSzn** [comment]
Hi @Nathan-MV,

I included a setting (``rgssScriptEditor.gameplay.useWine``) to enable/disable Wine usage on the extension settings page, make sure it is disabled if you want to run an mkxp-z executable (also, on the settings, make sure that the game path is set correctly to the mkxp-z executable).

![image](https://github.com/SnowSzn/rgss-script-editor/assets/134753051/d9c5099d-9b07-4c2c-8b51-f96474eb7eef)

![image](https://github.com/SnowSzn/rgss-script-editor/assets/134753051/b129cb06-ad8b-4f5c-9acd-0adb889a4f1d)
(This one should not end with ``.exe`` if it is a mkxp-z executable on other platform besides Windows)

As for now, the way the extension works to run the game in Mac/Linux is as follows:
1. Check if the flag to use Wine is active or not.
2. If it is active, check if Wine is installed.
2.1 If it is installed, Wine is used to run the executable.
2.2 If it is not, throws an exception informing about the problem.
3. If it is not active, and the executable seems to be a Windows executable (file ends with ``.exe``), it throws an exception informing that it is trying to run a Windows executable in Linux.
4. Otherwise, it is assumed that it is a Linux/Mac executable.

If the extension is not able to launch the executable after applying what I have said above, please attach the log file that the extension creates automatically (the debug option must be enabled in the extension settings)

**Comment by Nathan-MV** [comment]
Edit: It seems that is the case
