### ISSUE TITLE
Is there a script extension for sublime text?

### ISSUE THREAD

**Issue by arrosev** [SnowSzn/rgss-script-editor#3]
Hello, is there a scripting extension for sublime text?

**Comment by SnowSzn** [comment]
> Hello, is there a scripting extension for sublime text?

As far as I know, there is no plugin like this for Sublime, also porting RGSS Script Editor is not feasible due to the differences between VS Code and Sublime APIs, for example, the tree view RGSS Script Editor provides cannot be replicated in Sublime, I believe.

Is there any specific reason (related to the extension) you would avoid using it in VS Code?

**Comment by arrosev** [comment]
> > Hello, is there a scripting extension for sublime text?
> 
> As far as I know, there is no plugin like this for Sublime, also porting RGSS Script Editor is not feasible due to the differences between VS Code and Sublime APIs, for example, the tree view RGSS Script Editor provides cannot be replicated in Sublime, I believe.
> 
> Is there any specific reason (related to the extension) you would avoid using it in VS Code?

In fact, I had been using VS Code to write plug-ins, but I found that it was too slow to open, and the background is a serious memory hog, so I switched to sublime text. Thanks for the reply, I think I'll look into it and see if I can implement a similar plugin in sublime text, this repo should be a good reference!
